### ISSUE TITLE
MSSliceMaker.slicesFromExportableLayer is deprecated and will be removed in v40

### ISSUE THREAD

**Issue by bomberstudios** [Proto-io/sketch-protoio-export#1]
You need to use `MSExportRequest.exportRequestsFromExportableLayer()` instead : )

See https://github.com/Proto-io/sketch-protoio-export/search?utf8=✓&q=slicesFromExportableLayer

**Comment by alexisod** [comment]
Thanks for reporting but it's in a try/catch block to ensure backward compatibility. That should be ok for v40 right?

**Comment by bomberstudios** [comment]
Ah, right, I missed the context in the search result : )

Nothing to see here then, move along : )

**Comment by alexisod** [comment]
Thanks for checking, nevertheless!
